### ISSUE TITLE
Multi-key streams fail on IE 11

### ISSUE THREAD

**Issue by joeyparrish** [Axinom/dash-test-vectors#4]
Hi all,

As detailed in google/shaka-player#959, multi-key streams from the v7 test vectors are failing to play on IE 11, at least so far as Shaka Player is concerned.

Here's a quick link to reproduce: https://shaka-player-demo.appspot.com/demo/#asset=//media.axprod.net/TestVectors/v7-MultiDRM-MultiKey/Manifest.mpd;lang=en-US;play

The error code from Microsoft is `0x8004b896`.  Any idea what is causing this?  Are these test vectors supposed to work on IE?  Do they work in some other player?  Is this Shaka Player's bug?

Thanks!

**Comment by sandersaares** [comment]
I am not aware of the exact reason for this failure but I suspect that it is because IE11 is unable to cope with content where the PSSH box is not present in the media stream. I reported this to Microsoft last year and they fixed it in Edge for Creators Update but I imagine they might not consider this type of thing to pass the bar for inclusion in IE11.

As far as I know, the behavior with dash.js is equivalent, so this is almost certainly not a Shaka issue.

I have, however, not verified this theory so it is possible I am simply mistaken.

**Comment by joeyparrish** [comment]
So the v7 test vectors do not support IE 11?

**Comment by sandersaares** [comment]
The test vectors are designed to conform to industry specifications like DASH-IF IOP (where the appropriate usage of PSSH boxes with DASH is defined), so I would not say that the test vectors really "support" any particular browser. It is a question of the browsers (and the players) supporting playback of specification-conforming content (or not, as it were).

To give you another example, I recall that Android is unable to play back Clear Key content signaled in the way used in our test vectors and as specified in DASH-IF IOP (no PSSH in manifest nor media stream). ExoPlayer, I believe, works around this platform limitation (Android requires the W3C generic PSSH to initiate Clear Key license acquisition) by synthesizing the required PSSH at runtime based on information from the manifest (the `default_KID`).

In theory, a player might also work around this IE11 limitation by copying the PSSH from the manifest to the media stream when operating on IE11 (assuming this is indeed the limitation that prevents playback here).

**Comment by joeyparrish** [comment]
Thank you for the clarification.
